CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_NUMBER BIGINT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS OPERATION_TYPES (
    OPERATIONTYPE_ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL
);

INSERT INTO OPERATION_TYPES(OPERATIONTYPE_ID, DESCRIPTION) VALUES
(1, 'CASH PURCHASE'),
(2, 'INSTALLMENT PURCHASE'),
(3, 'WITHDRAWAL'),
(4, 'PAYMENT');

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT NOT NULL,
    OPERATIONTYPE_ID INT NOT NULL,
    AMOUNT DECIMAL(12, 2) NOT NULL,
    BALANCE DECIMAL(12, 2) DEFAULT 0.0,
    EVENT_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    CONSTRAINT fk_transactions_account
        FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),

    CONSTRAINT fk_transactions_operationtype
        FOREIGN KEY (OPERATIONTYPE_ID) REFERENCES OPERATION_TYPES (OPERATIONTYPE_ID),

    CONSTRAINT chk_transaction_amount_sign
      CHECK (
          (OPERATIONTYPE_ID IN (1,2,3) AND AMOUNT <= 0)
          OR
          (OPERATIONTYPE_ID = 4 AND AMOUNT >= 0)
      )
);